version: '3.8'
services:
  laravel:
    build: .
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:GY534XQwwEo/p77T85YXKvg37RBrsRw5svhsZ6pIFY4=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
